"""Build the C++ catalog from Snakify's public unit indexes and sample tests.

The generated catalog keeps titles, source URLs, and public input/output cases.
It intentionally does not mirror Snakify's copyrighted lesson prose.
"""

from __future__ import annotations

import ast
import html
import json
import re
import time
import urllib.request
from pathlib import Path


ROOT = "https://snakify.org"
OUTPUT = Path(__file__).resolve().parents[1] / "dist" / "problems.js"
UNITS = [
    ("print_input_numbers", "Input, print and numbers"),
    ("integer_float_numbers", "Integer and float numbers"),
    ("if_then_else_conditions", "Conditions: if, then, else"),
    ("for_loop_range", "For loop with range"),
    ("strings_str", "Strings"),
    ("while_loop", "While loop"),
    ("lists", "Lists"),
    ("functions", "Functions and recursion"),
    ("two_dimensional_lists_arrays", "Two-dimensional lists (arrays)"),
    ("sets", "Sets"),
    ("dictionaries_dicts", "Dictionaries"),
]


def fetch(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": "ButterflyJudgerCatalog/1.0"})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read().decode("utf-8")


def lesson_problems(slug: str) -> list[tuple[str, str]]:
    page = fetch(f"{ROOT}/en/lessons/{slug}/problems/")
    matches = re.findall(
        r'href="([^"]*/problems/[^"]+/?)"[^>]*>(.*?)</a>',
        page,
        flags=re.IGNORECASE | re.DOTALL,
    )
    result: list[tuple[str, str]] = []
    seen: set[str] = set()
    for href, raw_title in matches:
        if href in seen:
            continue
        title = html.unescape(re.sub(r"<[^>]+>", "", raw_title)).strip()
        if title:
            seen.add(href)
            result.append((title, href))
    return result


def public_tests(page: str) -> list[dict[str, str]]:
    match = re.search(r"window\.tests\s*=\s*(\[.*?\]);", page, flags=re.DOTALL)
    if not match:
        return []
    parsed = ast.literal_eval(match.group(1))
    return [
        {"input": str(case.get("input", "")) + "\n", "output": str(case.get("answer", "")) + "\n"}
        for case in parsed
    ]


def main() -> None:
    problems: list[dict[str, object]] = []
    units = [{"id": index, "title": title} for index, (_, title) in enumerate(UNITS, 1)]
    for unit, (slug, _) in enumerate(UNITS, 1):
        entries = lesson_problems(slug)
        for number, (title, href) in enumerate(entries, 1):
            source_url = ROOT + href if href.startswith("/") else href
            tests = public_tests(fetch(source_url))
            if not tests:
                raise RuntimeError(f"No public tests found for {source_url}")
            problems.append(
                {
                    "id": f"U{unit:02d}-{number:02d}",
                    "unit": unit,
                    "title": title,
                    "difficulty": f"Exercise {number}",
                    "summary": "Snakify original exercise, adapted for C++17 judging.",
                    "statement": f"完成 Snakify 原題「{title}」，並以標準輸入、標準輸出作答。請使用下方連結閱讀完整原題。",
                    "input": "輸入格式以 Snakify 原題為準。",
                    "output": "輸出格式以 Snakify 原題為準；空白與換行需符合題目要求。",
                    "sampleInput": tests[0]["input"].rstrip("\n"),
                    "sampleOutput": tests[0]["output"].rstrip("\n"),
                    "hint": "先把 Python 題意翻成語言無關的演算法，再處理 C++ 的輸入與輸出格式。",
                    "sourceUrl": source_url,
                    "tests": tests,
                }
            )
            time.sleep(0.03)

    starter = """#include <bits/stdc++.h>
using namespace std;

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    // Your C++17 solution
    return 0;
}
"""
    for problem in problems:
        problem["starter"] = starter

    payload = (
        "// Generated by tools/build_snakify_catalog.py from Snakify's public indexes and sample tests.\n"
        f"window.COURSE_UNITS = {json.dumps(units, ensure_ascii=False, indent=2)};\n\n"
        f"window.COURSE_PROBLEMS = {json.dumps(problems, ensure_ascii=False, indent=2)};\n"
    )
    OUTPUT.write_text(payload, encoding="utf-8")
    print(f"Generated {len(problems)} problems across {len(units)} units at {OUTPUT}")


if __name__ == "__main__":
    main()
